function Hd = Test_Filter
%TEST_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 18-Sep-2017 19:26:44

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 20;  % Sampling Frequency

N     = 10;  % Order
Fstop = 1;   % Stopband Frequency
Fpass = 2;   % Passband Frequency
Wstop = 1;   % Stopband Weight
Wpass = 1;   % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);
Hd = dfilt.dffir(b);

% [EOF]
